[project]
name = "kupio-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Vadim Popovych",email = "zyzel19@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.135.1,<0.136.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "sqlalchemy[async] (>=2.0.48,<3.0.0)",
    "pydantic-settings (>=2.13.1,<3.0.0)",
    "alembic (>=1.18.4,<2.0.0)",
    "msgspec (>=0.20.0,<0.21.0)",
    "uvicorn (>=0.41.0,<0.42.0)",
    "redis[asyncio] (>=7.3.0,<8.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "passlib[argon] (>=1.7.4,<2.0.0)",
    "argon2-cffi (>=25.1.0,<26.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.5"
pre-commit = "^4.5.1"

