"""promotions and balances

Revision ID: 006
Revises: 005
Create Date: 2026-04-04 19:35:00.424121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, Sequence[str], None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion_packets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum("TOP", "HIGHLIGHT", "URGENT", "VIP", name="promotiontype"),
            nullable=False,
        ),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column(
            "price",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "balance_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "amount",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("TOP_UP", "DEBIT", "REFUND", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_transactions_user_id"),
        "balance_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "listing_promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column(
            "packet_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACTIVE", "EXPIRED", "CANCELLED", name="promotionstatus"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["packet_id"],
            ["promotion_packets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["balance_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_promotions_listing_id"),
        "listing_promotions",
        ["listing_id"],
        unique=False,
    )
    op.create_index(
        "ix_listing_promotions_status_expires_at",
        "listing_promotions",
        ["status", "expires_at"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "balance",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
    )
    op.execute("UPDATE users SET balance = 0")
    op.alter_column("users", "balance", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    op.drop_index(
        "ix_listing_promotions_status_expires_at", table_name="listing_promotions"
    )
    op.drop_index(
        op.f("ix_listing_promotions_listing_id"), table_name="listing_promotions"
    )
    op.drop_table("listing_promotions")
    op.drop_index(
        op.f("ix_balance_transactions_user_id"), table_name="balance_transactions"
    )
    op.drop_table("balance_transactions")
    op.drop_table("promotion_packets")

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS promotiontype")
        op.execute("DROP TYPE IF EXISTS promotionstatus")
        op.execute("DROP TYPE IF EXISTS transactiontype")

    # ### end Alembic commands ###
