"""reports

Revision ID: 009
Revises: 008
Create Date: 2026-04-12 00:07:30.720305

"""

import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, Sequence[str], None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


report_reasons_table = sa.table(
    "report_reasons",
    sa.column("slug", sa.String(length=100)),
    sa.column("title", sa.String(length=255)),
    sa.column("description", sa.String(length=1000)),
    sa.column("display_order", sa.Integer()),
    sa.column("is_active", sa.Boolean()),
    sa.column("created_at", sa.DateTime()),
    sa.column("updated_at", sa.DateTime()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)
    op.create_table(
        "report_reasons",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "ix_report_reasons_active_display_order_id",
        "report_reasons",
        ["is_active", "display_order", "id"],
        unique=False,
    )
    op.bulk_insert(
        report_reasons_table,
        [
            {
                "slug": "other",
                "title": "Other",
                "description": "Other reason",
                "display_order": 0,
                "is_active": True,
                "created_at": now,
                "updated_at": None,
            }
        ],
    )
    op.create_table(
        "listing_reports",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("additional_info", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DECLINED",
                "LISTING_REMOVED",
                "USER_BANNED",
                name="reportstatus",
            ),
            nullable=False,
        ),
        sa.Column("seen_at", sa.DateTime(), nullable=True),
        sa.Column("seen_by_moderator_id", sa.UUID(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(), nullable=True),
        sa.Column("moderator_id", sa.UUID(), nullable=True),
        sa.Column("moderator_comment", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reason_id"],
            ["report_reasons.id"],
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["seen_by_moderator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_listing_reports_listing_id", "listing_reports", ["listing_id"], unique=False
    )
    op.create_index(
        "ix_listing_reports_reporter_id",
        "listing_reports",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        "ix_listing_reports_seen_created_id",
        "listing_reports",
        ["seen_at", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_listing_reports_status_created_id",
        "listing_reports",
        ["status", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_listing_reports_listing_reporter_pending",
        "listing_reports",
        ["listing_id", "reporter_id"],
        unique=True,
        sqlite_where=sa.text("status = 'PENDING'"),
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_listing_reports_listing_reporter_pending",
        table_name="listing_reports",
        sqlite_where=sa.text("status = 'PENDING'"),
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_listing_reports_status_created_id", table_name="listing_reports")
    op.drop_index("ix_listing_reports_seen_created_id", table_name="listing_reports")
    op.drop_index("ix_listing_reports_reporter_id", table_name="listing_reports")
    op.drop_index("ix_listing_reports_listing_id", table_name="listing_reports")
    op.drop_table("listing_reports")
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('DROP TYPE "reportstatus"')
    op.drop_index(
        "ix_report_reasons_active_display_order_id", table_name="report_reasons"
    )
    op.drop_table("report_reasons")
    # ### end Alembic commands ###
