"""add filter_definitions and custom_filters

Revision ID: 003
Revises: 002
Create Date: 2026-03-28 17:05:31.896321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, Sequence[str], None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter_definitions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "filter_type",
            sa.Enum("TEXT", "NUMBER", "BOOLEAN", "SELECT", "RANGE", name="filtertype"),
            nullable=False,
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_id", "slug", name="uq_filter_definitions_category_slug"
        ),
    )
    op.add_column("categories", sa.Column("icon", sa.String(length=255), nullable=True))
    op.add_column(
        "listings",
        sa.Column(
            "custom_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        "ix_listings_custom_filters",
        "listings",
        ["custom_filters"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_listings_custom_filters", table_name="listings", postgresql_using="gin"
    )
    op.drop_column("listings", "custom_filters")
    op.drop_column("categories", "icon")
    op.drop_table("filter_definitions")
    # ### end Alembic commands ###
