"""oauth

Revision ID: 003
Revises: 002
Create Date: 2026-03-29 14:49:39.489843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, Sequence[str], None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_sub", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_sub"),
        sa.UniqueConstraint("provider", "user_id"),
    )
    op.create_index(
        op.f("ix_oauth_identities_provider"),
        "oauth_identities",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_identities_provider_sub"),
        "oauth_identities",
        ["provider_sub"],
        unique=False,
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=512), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=512), nullable=False
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_index(
        op.f("ix_oauth_identities_provider_sub"), table_name="oauth_identities"
    )
    op.drop_index(op.f("ix_oauth_identities_provider"), table_name="oauth_identities")
    op.drop_table("oauth_identities")
    # ### end Alembic commands ###
